### ISSUE TITLE
opbeat-js needs a lot of unspecified dependencies

### ISSUE THREAD

**Issue by hakanw** [vanjacosic/opbeat-js#3]
When I'm trying to test opbeat-js and require it through browserify, I get a lot of these exceptions due dependencies that are not specified in the package.json.

```
Error: Cannot find module 'gulp-livereload' from '/Users/hakan/src/active_projects/P5/node_modules/opbeat-js'
    at /Users/hakan/src/active_projects/P5/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/Users/hakan/src/active_projects/P5/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/hakan/src/active_projects/P5/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/hakan/src/active_projects/P5/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/hakan/src/active_projects/P5/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/hakan/src/active_projects/P5/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15
```

Please make them hard dependencies so they will be automatically installed with npm, or somehow remove the dependencies.

Thanks!

**Comment by vanjacosic** [comment]
@hakanw Sorry for the really late reply.

I think the issue might be that I had mistakenly set the `main` option to be the wrong file. I have now fixed that mistake in the commit referenced above.

(GitHub autoclosed the issue when I pushed, but let me know if the problem still persists.)

As it says in the readme, this repo is not officially support and that's why I didn't spend any time preparing it for use with browserify etc. So if you have concrete ideas or more issues let me know - and PRs are very welcome, as you might know better how to deal with these things.
